#!/usr/bin/env bash

set -e

export OVE_LOCAL_ECHO=1

if ! command -v dmce; then
	echo "error: command 'dmce' missing"
	exit 1
fi

# run gcc/gplusplus-torture and DMCE unittests
ove test dmce

# run DMCE on tmux and make sure tmux builds
ove fetch tmux
ove dmce launch --cache -v -- tmux
ove status tmux
ove buildme-parallel tmux

# run coverage-history on ag
ove fetch ag
ove revtab-check 0
if [ -s "$HOME/.dmceconfig" ]; then
	sed -i -e 's,dmce-probe-user,dmce-probe-syslog,g' "$HOME/.dmceconfig"
fi
ove dmce-coverage-history ag ag 3 2.2.0 2.1.0 2.0.0 1.0.3 1.0.2 1.0.1 1.0.0
