#!/usr/bin/env bash

set -e

if [ -d "${OVE_ARCHIVE_DIR:?}" ]; then
	# remove any old DMCE packages laying around
	find "${OVE_ARCHIVE_DIR:?}" -mindepth 1 -mindepth 1 -name 'dmce-*' -exec rm {} \;
fi

if ! ove-dist dmce; then
	exit 1
elif ! d="$(find "${OVE_ARCHIVE_DIR:?}" -mindepth 1 -mindepth 1 -name 'dmce-*.xz' -type f)"; then
	exit 1
elif [ "x${d}" = "x" ]; then
	echo "error: DMCE package not found"
	exit 1
elif ! tar -C "$OVE_STAGE_DIR" -xf "${d}"; then
	echo "error: unpack '$d' failed"
	exit 1
elif ! command -v dmce-setup > /dev/null; then
	echo "error: 'dmce-setup' not found"
	exit 1
elif ! dmce-setup "$OVE_BASE_DIR"; then
	echo "error: 'dmce-setup $OVE_BASE_DIR' failed"
	exit 1
elif ! dmce_work_dir=$(ove dmce-get-work-dir); then
	echo "error: could not get DMCE work dir"
	exit 1
elif ! sed -i -e "s,${dmce_work_dir},/var${dmce_work_dir},g" "$OVE_BASE_DIR"/.dmceconfig; then
	echo "error: could not update work dir path"
	exit 1
fi
