#!/usr/bin/env bash

set -e

if ! command -v cram > /dev/null; then
	if command -v cram3 > /dev/null; then
		(mkdir -p "${OVE_STAGE_DIR:?}"/"${OVE_PREFIX}"/bin; cd "${OVE_STAGE_DIR:?}"/"${OVE_PREFIX}"/bin; ln -s "$(command -v cram3)" cram)
	else
		echo "error: cram not found, try:"
		echo "$ pip3 install cram"
		exit 1
	fi
fi

if ! grep -q ^test: Makefile; then
	echo "error: could not find the test target"
	exit 1
fi

timeout 60 make test
