#!/usr/bin/env bash

export OVE_DISTROCHECK_STEPS="user ssh"
echo "set -x;date;whoami;cat /etc/os-release;hostname;ip addr" > "${OVE_TMP:?}/a"
if [ -n "${TMUX}" ]; then
	__s="-parallel"
fi
ove-distrocheck${__s} \
	"${OVE_TMP}/a" \
	alpine/3.18$ \
	debian/trixie$ \
	ubuntu/22.04$
unset __s
if [ -n "${TMUX}" ]; then
	watch -d -x -- bash -c "lxc list|grep ${OVE_USER:?}-"
fi
