#!/usr/bin/env bash

export OVE_DISTROCHECK_STEPS="user ssh"
echo "set -x;date;whoami;hostname;ip addr" > "${OVE_TMP:?}/a"
if [ -n "${TMUX}" ]; then
	__s="-parallel"
fi
ove-distrocheck${__s} \
	"${OVE_TMP}/a" \
	alpine/3.1[4567]$ \
	ubuntu/2[02].[01][04]$
unset __s
