#!/usr/bin/env bash

if ! command -v clang-check > /dev/null; then
	echo "error: clang-check is not found"
	exit 1
fi

if [ $# -eq 0 ]; then
	repos=$(echo $OVE_REPO_LIST | \
			xargs -n1 | \
			grep -v /codechecker$ | \
			grep -v /dmce$ | \
			grep -v /ove-tutorial$ | \
			grep -v /.ove$)
else
	while true; do
		[ "$*" == "" ] && break

		# sanity checks
		if ! [ -d "$1" ] || \
			! [ -d "$1/.git" ] || \
			[ "$1" == "$OVE_BASE_DIR/codechecker" ] || \
			[ "$1" == "$OVE_BASE_DIR/dmce" ] || \
			[ "$1" == "$OVE_BASE_DIR/ove-tutorial" ] || \
			[ "$1" == "$OVE_BASE_DIR/.ove" ]; then
			shift
			continue
		fi
		repos+="$1 "
		shift
	done
fi

for p in $repos; do
	cd $p
	eval $DMCE_CLEANER
	eval $DMCE_LAUNCHER
done
