#!/usr/bin/env bash

alpine_release="edge"
debian_release="12"
ubuntu_release="24.04"

function init {
	if ! command -v incus > /dev/null; then
		echo "error: command incus not found" 1>&2
		exit 1
	fi

	if [ -n "${TMUX}" ]; then
		__s="-parallel"
	fi

	export OVE_INSTANCE_NAME_PREFIX=demo
	export OVE_INSTANCE_NAME_RANDOM=1
	export OVE_LOCAL_ECHO=1
}

function run {
	if [ $# -eq 0 ]; then
		t_list=$(compgen -A function | \
			while read -r line; do
				if [ ${#line} -ne 1 ]; then
					continue
				fi
				echo "$line"
			done | sort)
		else
			t_list="${*}"
	fi

	for t in ${t_list}; do
		if [ "$(type -t "$t")" != "function" ]; then
			continue
		fi
		$t
	done
}

function a {
	cat > "${OVE_TMP:?}"/a << EOF
#!/usr/bin/env sh
echo hi
c_list="date hostname whoami"
for c in \${c_list}; do
	if command -v "\$c" > /dev/null; then
		\$c
	fi
done
if [ -e /etc/os-release ]; then
	cat /etc/os-release
fi
EOF
	cat -n "$OVE_TMP"/a

	ove-echo cyan "test ${FUNCNAME[0]}: run the above shell script within three containers [press ENTER to start]"
	read -r -p ""

	export OVE_INSTANCE_STEPS=""
	ove-create-instance"${__s}" \
		"${OVE_TMP}/a" \
		alpine/${alpine_release:?}$ \
		debian/${debian_release:?}$ \
		ubuntu/${ubuntu_release:?}$
}

function b {
	ove-echo cyan "test ${FUNCNAME[0]}: build the OVE project 'foo' within a Ubuntu ${ubuntu_release:?} container, run the job as user, delete when done [press ENTER to start]"
	read -r -p ""

	export OVE_INSTANCE_STEPS="user"
	ove-create-instance"${__s}" \
		foo \
		ubuntu/${ubuntu_release:?}$
	}

function c {
	ove-echo cyan "test ${FUNCNAME[0]}: build the OVE project 'ag' within three containers [press ENTER to start]"
	read -r -p ""

	export OVE_INSTANCE_STEPS=""
	ove-create-instance"${__s}" \
		ag \
		alpine/${alpine_release:?}$ \
		centos/9-Stream$ \
		ubuntu/${ubuntu_release:?}$
}

function d {
	cat > "${OVE_TMP:?}"/a << EOF
#!/usr/bin/env sh
set -x
date
whoami
hostname
ip addr
EOF
	cat -n "$OVE_TMP"/a

	ove-echo cyan "test ${FUNCNAME[0]}: run the above shell script within a Ubuntu ${ubuntu_release:?} container, enable debug prints, leave the container running [press ENTER to start]"
	read -r -p ""

	export OVE_INSTANCE_STEPS="running verbose"
	ove-create-instance"${__s}" \
		"$OVE_TMP"/a \
		ubuntu/${ubuntu_release:?}$
}

function e {
	ove-echo cyan "test ${FUNCNAME[0]}: build the OVE project 'foo' within three containers, run the job as user, using worktree, delete container when done [press ENTER to start]"
	read -r -p ""

	export OVE_INSTANCE_STEPS="user worktree"
	ove-create-instance"${__s}" \
		foo \
		alpine/${alpine_release:?}$ \
		debian/${debian_release:?}$ \
		ubuntu/${ubuntu_release:?}$
}

function X {
	ove-echo cyan "test ${FUNCNAME[0]}: setup a Xfce desktop within an Alpine container [press ENTER to start]"
	read -r -p ""

	export OVE_INSTANCE_STEPS="X running ssh_config ssh user"
	export OVE_INSTANCE_XPRA_CLIENT_ARGS="attach"
	export OVE_INSTANCE_XPRA_DE_CMD="xfce4-session"
	export OVE_INSTANCE_XPRA_DE="xfce"
	ove-create-instance"${__s}" \
		true \
		alpine/${alpine_release:?}$
}

function Y {
	ove-echo cyan "test ${FUNCNAME[0]}: setup a MATE desktop within an Alpine container [press ENTER to start]"
	read -r -p ""

	export OVE_INSTANCE_STEPS="X running ssh_config ssh user verbose"
	export OVE_INSTANCE_XPRA_CLIENT_ARGS="attach"
	export OVE_INSTANCE_XPRA_DE_CMD="mate-session"
	export OVE_INSTANCE_XPRA_DE="mate"
	ove-create-instance"${__s}" \
		true \
		alpine/${alpine_release:?}$
}

function cleanup {
	local c_list

	ove-echo cyan "press ENTER to cleanup"
	read -r -p ""
	while true; do
		c_list=$(incus list --format csv | cut -d, -f1 | grep ^${OVE_INSTANCE_NAME_PREFIX}-)
		if [ "$c_list" = "" ]; then
			break
		fi
		eval incus delete -f "${c_list}" 2> /dev/null
		echo -n .
	done
	echo

	pkill -f ove_init
	pkill -f "incus list"
}

init
run "$@"
cleanup
