#!/usr/bin/env bash

! [ -e libevent-${libevent_version}-stable.tar.gz ] && \
		wget https://github.com/libevent/libevent/releases/download/release-${libevent_version}-stable/libevent-${libevent_version}-stable.tar.gz

tar xvf libevent-${libevent_version}-stable.tar.gz
cd libevent-${libevent_version}-stable
./autogen.sh
